//-----------------------------------------------------------------------------
// DFF-based synthesizable wrapper for RAMPDP_256X64_GL_M2_D2.v
// Automatically generated by generate_behavioral_rams.py
//----------------------------------------------------------------------------- 
module RAMPDP_256X64_GL_M2_D2 (
  // retention / power pins
  input        IDDQ,
  inout  wire  SVOP_0, SVOP_1, SVOP_2, SVOP_3,
              SVOP_4, SVOP_5, SVOP_6, SVOP_7,
  // sleep-mode enables
  input        SLEEP_EN_0, SLEEP_EN_1, SLEEP_EN_2, SLEEP_EN_3,
               SLEEP_EN_4, SLEEP_EN_5, SLEEP_EN_6, SLEEP_EN_7,
  input        RET_EN,

  // clocks
  input        CLK,
  input        CLK_R,
  input        CLK_W,

  // read/write enables
  input        RE,
  input        WE,

  // read address bits
  input  wire  RADR_7, RADR_6, RADR_5, RADR_4, RADR_3, RADR_2, RADR_1, RADR_0,
  // write address bits
  input  wire  WADR_7, WADR_6, WADR_5, WADR_4, WADR_3, WADR_2, WADR_1, WADR_0,

  // write data bits
  input  wire  WD_63, WD_62, WD_61, WD_60, WD_59, WD_58, WD_57, WD_56, WD_55, WD_54, WD_53, WD_52, WD_51, WD_50, WD_49, WD_48, WD_47, WD_46, WD_45, WD_44, WD_43, WD_42, WD_41, WD_40, WD_39, WD_38, WD_37, WD_36, WD_35, WD_34, WD_33, WD_32, WD_31, WD_30, WD_29, WD_28, WD_27, WD_26, WD_25, WD_24, WD_23, WD_22, WD_21, WD_20, WD_19, WD_18, WD_17, WD_16, WD_15, WD_14, WD_13, WD_12, WD_11, WD_10, WD_9, WD_8, WD_7, WD_6, WD_5, WD_4, WD_3, WD_2, WD_1, WD_0,
  // read data bits
  output reg   RD_63, RD_62, RD_61, RD_60, RD_59, RD_58, RD_57, RD_56, RD_55, RD_54, RD_53, RD_52, RD_51, RD_50, RD_49, RD_48, RD_47, RD_46, RD_45, RD_44, RD_43, RD_42, RD_41, RD_40, RD_39, RD_38, RD_37, RD_36, RD_35, RD_34, RD_33, RD_32, RD_31, RD_30, RD_29, RD_28, RD_27, RD_26, RD_25, RD_24, RD_23, RD_22, RD_21, RD_20, RD_19, RD_18, RD_17, RD_16, RD_15, RD_14, RD_13, RD_12, RD_11, RD_10, RD_9, RD_8, RD_7, RD_6, RD_5, RD_4, RD_3, RD_2, RD_1, RD_0
);

  // Derived parameters
  localparam DEPTH      = 256;
  localparam WIDTH      = 64;
  localparam ADDR_WIDTH = $clog2(DEPTH);

  // buses
  wire [ADDR_WIDTH-1:0] RA     = {RADR_7, RADR_6, RADR_5, RADR_4, RADR_3, RADR_2, RADR_1, RADR_0};
  wire [ADDR_WIDTH-1:0] WA     = {WADR_7, WADR_6, WADR_5, WADR_4, WADR_3, WADR_2, WADR_1, WADR_0};
  wire [WIDTH-1:0]      WD_bus = {WD_63, WD_62, WD_61, WD_60, WD_59, WD_58, WD_57, WD_56, WD_55, WD_54, WD_53, WD_52, WD_51, WD_50, WD_49, WD_48, WD_47, WD_46, WD_45, WD_44, WD_43, WD_42, WD_41, WD_40, WD_39, WD_38, WD_37, WD_36, WD_35, WD_34, WD_33, WD_32, WD_31, WD_30, WD_29, WD_28, WD_27, WD_26, WD_25, WD_24, WD_23, WD_22, WD_21, WD_20, WD_19, WD_18, WD_17, WD_16, WD_15, WD_14, WD_13, WD_12, WD_11, WD_10, WD_9, WD_8, WD_7, WD_6, WD_5, WD_4, WD_3, WD_2, WD_1, WD_0};
  reg  [WIDTH-1:0]      RD_bus;

  // memory array
  reg [WIDTH-1:0] mem [0:DEPTH-1];

  // write port (uses CLK_W)
  always @(posedge CLK_W) begin
    if (WE) mem[WA] <= WD_bus;
  end

  // read port (uses CLK_R)
  always @(posedge CLK_R) begin
    if (RE) RD_bus <= mem[RA];
  end

  // drive outputs
  assign {RD_63, RD_62, RD_61, RD_60, RD_59, RD_58, RD_57, RD_56, RD_55, RD_54, RD_53, RD_52, RD_51, RD_50, RD_49, RD_48, RD_47, RD_46, RD_45, RD_44, RD_43, RD_42, RD_41, RD_40, RD_39, RD_38, RD_37, RD_36, RD_35, RD_34, RD_33, RD_32, RD_31, RD_30, RD_29, RD_28, RD_27, RD_26, RD_25, RD_24, RD_23, RD_22, RD_21, RD_20, RD_19, RD_18, RD_17, RD_16, RD_15, RD_14, RD_13, RD_12, RD_11, RD_10, RD_9, RD_8, RD_7, RD_6, RD_5, RD_4, RD_3, RD_2, RD_1, RD_0} = RD_bus;

endmodule
